### ISSUE TITLE
iOS getBase64 method, does it work?

### ISSUE THREAD

**Issue by jgfidelis** [Snapp-FidMe/react-native-img-to-base64#1]
the method receives a `NSURL`.
According to doc, this are the types supported:
```
string (NSString)
number (NSInteger, float, double, CGFloat, NSNumber)
boolean (BOOL, NSNumber)
array (NSArray) of any types from this list
object (NSDictionary) with string keys and values of any type from this list
function (RCTResponseSenderBlock)
```

What you could do is receive the url as a `NSString` and convert it to `NSURL`, it is a simple fix.

I just wanted to know: does it currently work? I cannot test it right now, but will try later.

Thanks!

**Comment by Michaelvilleneuve** [comment]
Hey, yes it is working, no need to convert it from NSString to NSUrl. :)
