### ISSUE TITLE
TypeError: Cannot read property 'getBase64String' of undefined in react-native : 0.61.2

### ISSUE THREAD

**Issue by gilshaan** [Snapp-FidMe/react-native-img-to-base64#15]

**Comment by gilshaan** [comment]
I used another package: ` react-native-fs`
`import RNFS from 'react-native-fs';`
`var data = await RNFS.readFile( "file://path-to-file", 'base64').then(res => { return res });`
This works fine.

**Comment by akiladevinda** [comment]
@gilshaan   hi what is file://path-to-file ???? can you help me
